import Head from "next/head";
import Link from "next/link";
import { getAllPublished } from "../lib/notion";
import Layout from "../components/layout";

export default function Home({ posts }) {
  if (!posts) return <h1>No posts</h1>;

  return (
    <Layout>
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline text-red-100">Blog</h1>
        {posts.map((post, index) => (
          <section key={index}>
            <div>
              <h2>
                <Link href={`/posts/${post.slug}`}>{post.title}</Link>
              </h2>
              <div>
                <div>{post.date}</div>
                <p>{post.description}</p>
              </div>
            </div>
          </section>
        ))}
      </main>
    </Layout>
  );
}

export const getStaticProps = async () => {
  const data = await getAllPublished();

  return {
    props: {
      posts: data,
    },
    revalidate: 60,
  };
};
