import Head from "next/head";
import Link from "next/link";
import { getAllPublished } from "../lib/notion";
import Layout from "../components/layout";
import Image from "next/image";

export default function Home({ posts }) {
  if (!posts) return <h1>No posts</h1>;

  return (
    <Layout home={true}>
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Blog</h1>
        <div className="w-36 h-36 overflow-hidden rounded-full relative">
          <Image
            src="/images/profile.jpg"
            alt="profile"
            fill
            property
            className="object-cover object-left"
          />
        </div>

        <p>Hi, I'm Stanley. I'm a software engineer</p>
        {posts.map((post, index) => (
          <div key={index} className="my-4">
            <h2>
              <Link href={`/posts/${post.slug}`}>{post.title}</Link>
            </h2>
            <div>
              <div>{post.date}</div>
              <p>{post.description}</p>
            </div>
          </div>
        ))}
      </main>
    </Layout>
  );
}

export const getStaticProps = async () => {
  const data = await getAllPublished();

  return {
    props: {
      posts: data,
    },
    revalidate: 60,
  };
};
